# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-66a8c6d7-75d6-4da0-b735-9afdb9db84b1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-66a8c6d7-75d6-4da0-b735-9afdb9db84b1".device = "/dev/disk/by-uuid/66a8c6d7-75d6-4da0-b735-9afdb9db84b1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7DD6-B328";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d2879559-8f56-4cf4-9b57-12a66d051a2e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
